service: app-cognito-dio

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:751458874244:table/products

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
  insertProduct:
    handler: src/insertProduct.handler
    events:
      - http:
          path: /product
          method: post
  fetchProducts:
    handler: src/fetchProducts.handler
    events:
      - http:
          path: /products
          method: get
  fetchProduct:
    handler: src/fetchProduct.handler
    events:
      - http:
          path: /product/{id}
          method: get
  updateProduct:
    handler: src/updateProduct.handler
    events:
      - http:
          path: /product/{id}
          method: put


resources:
  Resources:
    tableProducts:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: products
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
