service: projeto-dio-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: users
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
            - AttributeName: username
              AttributeType: S
            - AttributeName: email
              AttributeType: S
            - AttributeName: password
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH          
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
